# Generated by Django 4.0.3 on 2022-05-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoesdata',
            name='image',
            field=models.ImageField(upload_to='shoes_data/'),
        ),
    ]
