# Generated by Django 4.0.3 on 2022-05-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_datagroup_photo_delete_shoesdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shoes_data/')),
            ],
        ),
        migrations.RemoveField(
            model_name='photo',
            name='data_group',
        ),
        migrations.DeleteModel(
            name='DataGroup',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
