# Generated by Django 4.0.3 on 2022-06-01 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shoes_data/%Y/%m/%d')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='TopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topcategory', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=64)),
                ('topcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.topcategory')),
            ],
            options={
                'ordering': ['topcategory'],
            },
        ),
        migrations.CreateModel(
            name='LabeledPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topcategory', models.CharField(max_length=64)),
                ('subcategory', models.CharField(max_length=64)),
                ('labeler', models.CharField(max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('labeled_image', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='labeled_image', to='photo.photo')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ExamPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspector', models.CharField(max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('exam_image', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='exam_image', to='photo.labeledphoto')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
