# Generated by Django 4.0.3 on 2022-05-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_alter_photo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_category', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['top_category'],
            },
        ),
    ]
