# Generated by Django 4.0.3 on 2022-05-10 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_topcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=64)),
                ('top_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top', to='photo.topcategory')),
            ],
            options={
                'ordering': ['top_category'],
            },
        ),
    ]
