# Generated by Django 4.0.3 on 2022-05-10 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabeledPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_category', models.CharField(max_length=64)),
                ('sub_category', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('labeled_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labeled_image', to='photo.photo')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
