# Generated by Django 4.0.3 on 2022-05-20 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_labeledphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='labeled',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='labeledphoto',
            name='labeled_image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='labeled_image', to='photo.photo'),
        ),
    ]
