# Generated by Django 4.0.3 on 2022-05-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0008_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='labeled',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
