# Generated by Django 4.0.3 on 2022-05-23 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0009_photo_labeled_delete_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topcategory',
            options={},
        ),
    ]
