# Generated by Django 4.0.3 on 2022-05-24 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0010_alter_topcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['topcategory']},
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='sub_category',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='topcategory',
            old_name='top_category',
            new_name='topcategory',
        ),
        migrations.RemoveField(
            model_name='labeledphoto',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='labeledphoto',
            name='top_category',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='top_category',
        ),
        migrations.AddField(
            model_name='labeledphoto',
            name='subcategory',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='photo.subcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labeledphoto',
            name='topcategory',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='photo.topcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='topcategory',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='photo.topcategory'),
            preserve_default=False,
        ),
    ]
