# Generated by Django 4.0.3 on 2022-05-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0011_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeledphoto',
            name='subcategory',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='labeledphoto',
            name='topcategory',
            field=models.CharField(max_length=64),
        ),
    ]
