# Generated by Django 4.0.3 on 2022-05-24 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0012_alter_labeledphoto_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeledphoto',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='labeledphoto',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.subcategory'),
        ),
        migrations.AlterField(
            model_name='labeledphoto',
            name='topcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.topcategory'),
        ),
    ]
