# Generated by Django 4.0.3 on 2022-05-25 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0014_alter_labeledphoto_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='updated',
        ),
    ]
