# Generated by Django 4.0.3 on 2022-05-29 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0016_labeledphoto_labeler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='labeled',
        ),
    ]
