# Generated by Django 4.0.3 on 2022-06-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0019_alter_examphoto_inspector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examphoto',
            name='inspector',
            field=models.CharField(max_length=32),
        ),
    ]
